name         'rfletcher-iotop'
version      '0.0.1'
license      'MIT License'
summary      'A puppet module for Iotop'
description  'Install or remove Iotop'
project_page 'https://github.com/rfletcher/puppet-iotop'
